### ISSUE TITLE
Build Error on Ubuntu 18.04 with GCC-7

### ISSUE THREAD

**Issue by liv-daliberti** [Alibaba-Gemini-Lab/Gemini-SEAL-BGV#1]
Hello -

I tried to build the codebase in accordance with the instructions for an Ubuntu 18.04 system with GCC-7, but it failed!

[ 56%] Building CXX object CMakeFiles/seal.dir/native/src/seal/util/rns.cpp.o

/home/ubuntu/SEAL/native/src/seal/util/rns.cpp: In instantiation of ‘seal::util::RNSTool::mod_t_and_divide_q_last_inplace(seal::util::RNSIter, seal::MemoryPoolHandle) const::<lambda(auto:91)>::<lambda(auto:92)> [with auto:92 = std::tuple<long unsigned int&, long unsigned int&, long unsigned int&>; auto:91 = std::tuple<seal::util::PtrIter<long unsigned int*>, seal::util::PtrIter<long unsigned int*>, const seal::Modulus&, seal::util::MultiplyUIntModOperand&>]’:
/home/ubuntu/SEAL/native/src/seal/util/common.h:35:21:   required from ‘ForwardIt seal::util::seal_for_each_n(ForwardIt, Size, Func&&) [with ForwardIt = seal::util::IterTuple<seal::util::PtrIter<long unsigned int*>, seal::util::PtrIter<long unsigned int*>, seal::util::PtrIter<long unsigned int*> >; Size = long unsigned int; Func = seal::util::RNSTool::mod_t_and_divide_q_last_inplace(seal::util::RNSIter, seal::MemoryPoolHandle) const::<lambda(auto:91)> [with auto:91 = std::tuple<seal::util::PtrIter<long unsigned int*>, seal::util::PtrIter<long unsigned int*>, const seal::Modulus&, seal::util::MultiplyUIntModOperand&>]::<lambda(auto:92)>]’
/home/ubuntu/SEAL/native/src/seal/util/rns.cpp:1245:33:   required from ‘seal::util::RNSTool::mod_t_and_divide_q_last_inplace(seal::util::RNSIter, seal::MemoryPoolHandle) const::<lambda(auto:91)> [with auto:91 = std::tuple<seal::util::PtrIter<long unsigned int*>, seal::util::PtrIter<long unsigned int*>, const seal::Modulus&, seal::util::MultiplyUIntModOperand&>]’
/home/ubuntu/SEAL/native/src/seal/util/common.h:35:21:   required from ‘ForwardIt seal::util::seal_for_each_n(ForwardIt, Size, Func&&) [with ForwardIt = seal::util::IterTuple<seal::util::RNSIter, seal::util::RNSIter, seal::util::PtrIter<const seal::Modulus*>, seal::util::PtrIter<seal::util::MultiplyUIntModOperand*> >; Size = long unsigned int; Func = seal::util::RNSTool::mod_t_and_divide_q_last_inplace(seal::util::RNSIter, seal::MemoryPoolHandle) const::<lambda(auto:91)>]’
/home/ubuntu/SEAL/native/src/seal/util/rns.cpp:1256:18:   required from here
/home/ubuntu/SEAL/native/src/seal/util/rns.cpp:1243:48: internal compiler error: in tsubst_copy, at cp/pt.c:14588
                     const uint64_t Lqi = get<2>(I).value() << 1;
                                          ~~~~~~^~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
CMakeFiles/seal.dir/build.make:471: recipe for target 'CMakeFiles/seal.dir/native/src/seal/util/rns.cpp.o' failed
make[2]: *** [CMakeFiles/seal.dir/native/src/seal/util/rns.cpp.o] Error 1
CMakeFiles/Makefile2:222: recipe for target 'CMakeFiles/seal.dir/all' failed
make[1]: *** [CMakeFiles/seal.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2


Please advise (and let me know if any additional information is needed!)

![image](https://user-images.githubusercontent.com/34242908/120817586-d1d53100-c51f-11eb-884c-74296e5c92a7.png)

**Comment by fionser** [comment]
It seems a gcc bug. Please try other compiler such as clang.

**Comment by liv-daliberti** [comment]
The push from 25 days ago fixed my build issue. Thank you!
